# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'eventgroups',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'eventusers',
                'ordering': ['-id'],
            },
        ),
    ]
